In [47]:

from statistics import mean

import seaborn as sns
import networkx as nx

import pandas as pd
import time
import datetime

In [48]:
data = pd.read_csv('bill/hotStuff.csv')

In [49]:
data.head()

,url,WeekID,Week Position,Song,Performer,SongID,Instance,Previous Week Position,Peak Position,Weeks on Chart
0,http://www.billboard.com/charts/hot-100/1958-0...,8/2/1958,1,Poor Little Fool,Ricky Nelson,Poor Little FoolRicky Nelson,1,NaN,1,1
1,http://www.billboard.com/charts/hot-100/1995-1...,12/2/1995,1,One Sweet Day,Mariah Carey & Boyz II Men,One Sweet DayMariah Carey & Boyz II Men,1,NaN,1,1
2,http://www.billboard.com/charts/hot-100/1997-1...,10/11/1997,1,Candle In The Wind 1997/Something About The Wa...,Elton John,Candle In The Wind 1997/Something About The Wa...,1,NaN,1,1
3,http://www.billboard.com/charts/hot-100/2006-0...,7/1/2006,1,Do I Make You Proud,Taylor Hicks,Do I Make You ProudTaylor Hicks,1,NaN,1,1
4,http://www.billboard.com/charts/hot-100/2009-1...,10/24/2009,1,3,Britney Spears,3Britney Spears,1,NaN,1,1

In [52]:
s="11/09/2001"
int(s[-4:])

2001

In [53]:
data["ANO"]=int(data["WeekID"][-4:])

TypeError: cannot convert the series to <class 'int'>

In [54]:
def ano(row):
   return int(row["WeekID"][-4:])

In [55]:
data['ANO'] = data.apply (lambda row: ano(row), axis=1)

In [63]:
dataPBANO=data[data["ANO"]>=2000]

In [72]:
dataPBANO[dataPBANO["Song"]=="Radioactive"].head(400)

,url,WeekID,Week Position,Song,Performer,SongID,Instance,Previous Week Position,Peak Position,Weeks on Chart,ANO
1133,http://www.billboard.com/charts/hot-100/2010-1...,10/2/2010,37,Radioactive,Kings Of Leon,RadioactiveKings Of Leon,1,NaN,37,1,2010
2642,http://www.billboard.com/charts/hot-100/2012-1...,12/8/2012,76,Radioactive,Imagine Dragons,RadioactiveImagine Dragons,2,71.0,71,13,2012
2871,http://www.billboard.com/charts/hot-100/2012-1...,12/15/2012,72,Radioactive,Imagine Dragons,RadioactiveImagine Dragons,2,76.0,71,14,2012
5679,http://www.billboard.com/charts/hot-100/2012-1...,12/22/2012,65,Radioactive,Imagine Dragons,RadioactiveImagine Dragons,2,72.0,65,15,2012
5869,http://www.billboard.com/charts/hot-100/2012-1...,12/29/2012,55,Radioactive,Imagine Dragons,RadioactiveImagine Dragons,2,65.0,55,16,2012
...,...,...,...,...,...,...,...,...,...,...,...
81484,http://www.billboard.com/charts/hot-100/2012-1...,11/17/2012,87,Radioactive,Imagine Dragons,RadioactiveImagine Dragons,2,90.0,87,10,2012
81732,http://www.billboard.com/charts/hot-100/2012-1...,11/24/2012,83,Radioactive,Imagine Dragons,RadioactiveImagine Dragons,2,87.0,83,11,2012
81958,http://www.billboard.com/charts/hot-100/2012-1...,12/1/2012,71,Radioactive,Imagine Dragons,RadioactiveImagine Dragons,2,83.0,71,12,2012
164721,http://www.billboard.com/charts/hot-100/2010-1...,10/9/2010,95,Radioactive,Kings Of Leon,RadioactiveKings Of Leon,1,37.0,37,2,2010
165241,http://www.billboard.com/charts/hot-100/2012-0...,8/25/2012,98,Radioactive,Imagine Dragons,RadioactiveImagine Dragons,1,93.0,93,2,2012